version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  labels:
  - "PR: Dependencies :nut_and_bolt:"
  ignore:
  - dependency-name: tldts-experimental
    versions:
    - 5.7.24
  - dependency-name: auto
    versions:
    - 10.23.0
  - dependency-name: rollup
    versions:
    - 2.43.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
